name: CI

on:
  push:
    tags:
      v*.*.*

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install -g npm@7 && npm ci
      - name: Run tests
        run: npm test
      - name: Create a production build
        run: npm run build && tar -czvf build.tgz build/
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
